### ISSUE TITLE
More than one Instance now causing Client.InvalidInstanceID.Malformed: Invalid id:

### ISSUE THREAD

**Issue by saschamcdonald** [oliverlloyd/jmeter-ec2#36] opened 2015-04-30 07:52 UTC
When I request one Instance all works really well. When I request more than one instance I have recently been receiving the following error: Client.InvalidInstanceID.Malformed: Invalid id: (instance id's)
This appears to be an issue with the following line of code:
count_passed=$(ec2-describe-instance-status --region $REGION ${attempted_instanceids[@]} | awk '/INSTANCESTATUS/ {print $3}' | grep -c passed)

The instances are actually initiated. However the script fails due to the error above. I am trying to debug but without too much success at present.- any ideas?

**Comment by oliverlloyd** [comment] 2016-03-28 12:24
I'm not able to reproduce this. The latest AMIs are working fine. I suspect it may have related to `ec2-describe-instances` returning differently formatted results when using EC2 vs. VPC? Given: 

1. EC2 accounts are now quite rare and old I'm inclined to limit support to VPC requests, certainly I will only be testing using VPC.

2. A change was implemented that could well have fixed this.

I'm closing for now.

**Closed by oliverlloyd** 2016-03-28 12:24 UTC
